title: SunRuiFans' Website
subtitle: A website for Sun Rui (Three) from SNH48 group.
description: >- # this means to ignore newlines until "baseurl:"
  A collection of Sunrui's videos, photos and etc.

url: "https://SunruiFans.github.io" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /blog

urls:
    - text: 关于孙芮
      url: /about
    - text: 新鲜事
      url: /blog
    - text: 美图
      url: /gallery
    - text: 打笔巨款
      url : /shop
    - text: 联系本站
      url : /contact
    #- text: Styleguide
    #  url: /styleguide
    # - text: Get Started
    #  url: /get-started

# Edit these details

author_logo: profile.png
author: Sun Rui
author_bio: 孙芮（1995年7月29日－），中国偶像团体SNH48的成员，所属队伍是Team SII。她于2013年8月18日SNH48第二期成员发表记者会中披露，成为SNH48的2期生并正式出道。2020年1月，参加爱奇艺女团青春成长节目《青春有你第二季》，获得第17名；8月15日，参加“创造炙热的青春”SNH48 GROUP第七届偶像年度人气总决选，获得冠军。
author_email: "待定"
author_location: 中国，上海
author_website_url: "https://sunruifans.github.io"
typewrite-text: “Hello 大家好，我是SNH48的孙芮。大家可以叫我‘芮哥’或者是‘三哥’。”

author_work_experiences:
            - company_name: 涂酷（TOO COOL FOR SCHOOL）
              company_logo: tuku_pic.jpg
              company_url: https://toocoolforschool.tmall.hk
              designation: 涂酷品牌彩妆大使
              description: 涂酷果冻眼影、涂酷果冻修容、涂酷幻想唇釉、涂酷三色立体修容
              visibility: true
            - company_name: 法国美帕（MedSPA）
              company_logo: meipa_pic.jpg
              company_url: https://medspaglobal.tmall.hk
              designation: 中国区面膜代言人暨治愈大使
              description: 美帕壳聚糖肌肤修复面膜
              visibility: true
            - company_name: 上海丝芭文化传媒集团有限公司
              company_logo: 48_pic.jpg
              company_url: https://www.48.cn/
              designation: 旗下艺人
              description: SNH48 Group成员，第七届偶像年度人气总决选冠军
              visibility: true

author_education_details:
              - college_logo: mit.png
                college_name: MIT
                college_url: https://mit.org
                college_degree: CS Engineer
                description: Bachelor of Technology
                visibility: true

author_project_details:
              - project_thumbnail: gamershub.png
                project_title: Gamers Hub
                project_description: A Platform built for Gamers and Game Devs
                project_url: https://gamershub.in
                visibility: true
              - project_thumbnail: hack4r.PNG
                project_title: Hack4r
                project_description: A Platform built for Hackers and Penetration Testers
                project_url: https://hack4r.com
                visibility: true

# social links
# twitter_username: johndoe
# github_username:  sujaykundu777
# facebook_username: johndoe
# linkedin_username: johndoe
# behance_username: johndoe
# instagram_username: johndoe
# medium_username: johndoe
# telegram_username: johndoe
# dribbble_username: johndoe
# flickr_username: johndoe
weibo_username: 也没那么爱读书

#for comments ( we got Disqus and Hyvor Commenting, uncomment the one you want to use )

# disqus_shortname: sujay-kundu
hyvor_talk_website_id: 476

# wakatime username (coding activity)
wakatime_username: sujaykundu777

# mailchimp embedded form url (newsletter):
mailchimp_form_url: https://sujaykundu.us10.list-manage.com/subscribe/post?u=50bab1c85eae24ecfb0f68361&amp;id=3a2dd721d0

# formspree (contact form)
formspree_email: 965036102@qq.com

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# Choose what to show ( can be true or false)
show_author_work_experiences: true
show_author_education_details: false
show_author_project_details: false

# pagination of posts
paginate: 4
per_page: 4
paginate_path: "/blog/page/:num/"

# minify
# compress_html:
#   clippings: all
#   comments: ["<!-- ", " -->"]
#   endings: all
#   ignore:
#     envs: ['development']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'

# Shop
collections:
 - products

# Gallery
defaults:
  -
    scope:
      path: "gallery"
    values:
      permalink: /:path/:basename:output_ext

# Build settings
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-menus


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

destination: ./build
